# Generated by Django 6.0.4 on 2026-05-01 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_clientprofile_commandeclient_commandeclientitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reservation', 'Réservation'), ('commande', 'Commande'), ('commande_prete', 'Commande prête'), ('reservation_confirmee', 'Réservation confirmée'), ('reservation_annulee', 'Réservation annulée')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('role_cible', models.CharField(choices=[('all', 'Tous'), ('gerant', 'Gérant'), ('chef', 'Chef'), ('serveur', 'Serveur'), ('caissier', 'Caissier'), ('client', 'Client')], default='all', max_length=20)),
                ('lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.commande')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
