# Generated by Django 6.0.3 on 2026-05-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='valide',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('gerant', 'Gérant'), ('chef', 'Chef cuisinier'), ('serveur', 'Serveur'), ('caissier', 'Caissier')], default='serveur', max_length=20),
        ),
    ]
