# Generated by Django 6.0.4 on 2026-05-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_avis_valide_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positif', 'Positif'), ('neutre', 'Neutre'), ('negatif', 'Négatif')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
