# Generated by Django 6.0.4 on 2026-05-26 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_avis_note_bert'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='commande_staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_client_liee', to='restaurant.commande'),
        ),
    ]
